### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'close'

### ISSUE THREAD

**Issue by shubhamtechgeek** [dataprofessor/streamlit_freecodecamp#2]
Hello there I am new to programming entirely. But I found this a little easy so I thought of starting from here. I managed to download and install Anaconda, make a new environment, write the entire code but at last I am having problems with the streamlit app. It says [AttributeError: 'DataFrame' object has no attribute 'close']
The programme is same 2 same. If you could point me into the right direct that would be great
I am attaching snapshot of the issue.

AttributeError: 'DataFrame' object has no attribute 'close'
Traceback:
File "c:\programdata\anaconda3\lib\site-packages\streamlit\script_runner.py", line 337, in _run_script
    exec(code, module.__dict__)
File "C:\Users\shubh\PycharmProjects\pythonProject1\1.py", line 21, in <module>
    st.line_chart(tickerDf.close)
File "c:\programdata\anaconda3\lib\site-packages\pandas\core\generic.py", line 5139, in __getattr__
    return object.__getattribute__(self, name)

![5454576](https://user-images.githubusercontent.com/61646160/115264211-b8d11600-a153-11eb-9058-d2714f58452a.JPG)

**Comment by Sachin-crypto** [comment]
It's 'Close' 
st.line_chart(tickerDf.Close)
